// <auto-generated />
using System;
using FunincasaDevelopment.Services.RecipeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunincasaDevelopment.Services.RecipeApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250217113149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FunincasaDevelopment.Services.RecipeApi.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<string>("RecipeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CookTime = 15,
                            CreatedOn = new DateTime(2025, 2, 17, 11, 31, 49, 126, DateTimeKind.Utc).AddTicks(3004),
                            ImageUrl = "https://example.com/spaghetti.jpg",
                            Ingredients = "[\"Spaghetti\",\"Eggs\",\"Parmesan Cheese\",\"Pancetta\",\"Black Pepper\"]",
                            Instructions = "Cook spaghetti. Fry pancetta. Mix eggs and cheese. Combine all with spaghetti.",
                            LastUpdated = new DateTime(2025, 2, 17, 11, 31, 49, 126, DateTimeKind.Utc).AddTicks(3230),
                            PrepTime = 10,
                            RecipeDescription = "A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.",
                            RecipeTitle = "Spaghetti Carbonara",
                            Servings = 2
                        },
                        new
                        {
                            RecipeId = 2,
                            CookTime = 30,
                            CreatedOn = new DateTime(2025, 2, 17, 11, 31, 49, 126, DateTimeKind.Utc).AddTicks(3434),
                            ImageUrl = "https://example.com/chicken-curry.jpg",
                            Ingredients = "[\"Chicken\",\"Onion\",\"Garlic\",\"Curry Powder\",\"Coconut Milk\"]",
                            Instructions = "Sauté onions and garlic. Add chicken and spices. Pour coconut milk and simmer.",
                            LastUpdated = new DateTime(2025, 2, 17, 11, 31, 49, 126, DateTimeKind.Utc).AddTicks(3435),
                            PrepTime = 15,
                            RecipeDescription = "A flavorful Indian-style chicken curry cooked with spices and coconut milk.",
                            RecipeTitle = "Chicken Curry",
                            Servings = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
